import { useEffect, useState } from 'react'
import { api, getUser } from '../api'

export default function CriarChamado({navigate,user}){
 const current=user||getUser(); const [titulo,setTitulo]=useState(''); const [desc,setDesc]=useState(''); const [categoria,setCategoria]=useState(''); const [prioridade,setPrioridade]=useState('Média'); const [equipamento,setEquipamento]=useState(''); const [setor,setSetor]=useState(''); const [equipamentos,setEquipamentos]=useState([]); const [erro,setErro]=useState(''); const [loading,setLoading]=useState(false); const [created,setCreated]=useState(null)
 useEffect(()=>{api('/equipamentos').then(setEquipamentos).catch(e=>setErro(e.message))},[])
 async function submit(){setErro('');if(!titulo.trim()||!desc.trim()||!categoria||!equipamento){setErro('Preencha título, categoria, descrição e equipamento/local.');return}setLoading(true);try{const r=await api('/chamados',{method:'POST',body:JSON.stringify({titulo,descricao:desc,categoria,prioridade,id_usuario:current?.id_usuario,num_equipamento:Number(equipamento),setor})});setCreated(r.chamado)}catch(e){setErro(e.message)}finally{setLoading(false)}}
 return <main className="form-screen"><header className="form-top"><button onClick={()=>navigate('/painel')} className="back">‹</button><div className="taskcall-logo"><b>✓ FIEC</b><span>Taskcall</span></div><div className="steps"><span className="on">1</span><i></i><span className={created?'on':''}>{created?'✓':'2'}</span><i></i><span className={created?'on':''}>3</span></div></header>
 <section className="ticket-form"><div className="form-title"><div><div className="eyebrow">NOVO CHAMADO</div><h1>Fazer Chamado</h1><p>Abra uma solicitação para a equipe responsável.</p></div><div className="form-actions"><button className="ghost" onClick={()=>navigate('/painel')}>Cancelar</button>{created?<button className="red-btn" onClick={()=>navigate('/inbox')}>Ver chamado</button>:<button className="red-btn" disabled={loading} onClick={submit}>{loading?'Enviando...':'Próximo'}</button>}</div></div>
 {created?<div className="success-box"><div className="success">✓</div><h2>Chamado criado com sucesso</h2><p>Chamado <b>#{created.cod_chamado}</b> registrado como <b>Aberto</b>.</p><button className="red-btn" onClick={()=>navigate('/inbox')}>Abrir Inbox</button></div>:<div className="form-grid">
 <label>Título do chamado<input value={titulo} onChange={e=>setTitulo(e.target.value)} placeholder="Digite o título do chamado" maxLength={100}/></label>
 <label>Categoria<select value={categoria} onChange={e=>setCategoria(e.target.value)}><option value="">Selecione uma categoria</option><option>Hardware</option><option>Software</option><option>Rede</option><option>Sistema</option><option>Equipamentos</option></select></label>
 <label className="wide">Descrição<textarea value={desc} onChange={e=>setDesc(e.target.value)} maxLength={5000} placeholder="Descreva o problema com o máximo de detalhes possível."></textarea><div className="editor"><b>B</b><i>I</i><u>U</u><s>S</s><span>⌁</span><span>＋</span><small>{desc.length}/5000</small></div></label>
 <label>Prioridade<select value={prioridade} onChange={e=>setPrioridade(e.target.value)}><option>Baixa</option><option>Média</option><option>Alta</option><option>Urgente</option></select></label>
 <label>Equipamento / local<select value={equipamento} onChange={e=>setEquipamento(e.target.value)}><option value="">Selecione</option>{equipamentos.map(eq=><option key={eq.num_equipamentos} value={eq.num_equipamentos}>Sala {eq.num_sala} — {eq.equipamentos_col||'Equipamento'} (#{eq.num_equipamentos})</option>)}</select></label>
 <label>Setor<input value={setor} onChange={e=>setSetor(e.target.value)} placeholder="Ex.: Laboratório 03"/></label><label>Solicitante<input value={current?.nome||current?.email||''} disabled/></label>
 {erro&&<div className="form-error wide">{erro}</div>}</div>}</section></main>
}
